<H3>Eine &Uuml;bersetzung bedeutet mehr als nur &Uuml;bersetzen</H3>

<p>Unterschiedliche &Uuml;bersetzungsaufgaben erfordern unterschiedliche Prozesse.  So bewegt sich ein technischer Bericht, der einfach nur von in einem anderen Land ans&auml;ssigen Kollegen verstanden werden muss, eine ganz andere Herangehensweise als eine wichtige Schnittstelle zwischen Ihnen und einem strategischen Markt. Auch die Prozesse der Qualit&auml;tspr&uuml;fung unterscheiden sich hierbei. Aus diesem Grund arbeiten wir mit einem modularen Arbeitsablauf mit Schritten, die Sie f&uuml;r Ihr jeweiliges Projekt und Ihre Texte entweder integrieren oder ausschlie&szlig;en k&ouml;nnen.</p>

<p>Der anspruchsvollste und zeitintensivste Teil eines &Uuml;bersetzungsprojekts ist zwar immer die eigentliche &Uuml;bersetzungsarbeit durch den/die &Uuml;bersetzer/in, allerdings gibt es jenseits dieser Kernarbeit eine Reihe von Schritten, die erledigt werden m&uuml;ssen, bevor &uuml;berhaupt &uuml;bersetzt werden kann. Ebenso m&uuml;ssen nach Fertigstellung der &Uuml;bersetzung entsprechende Ma&szlig;nahmen ergriffen werden, um die bestm&ouml;gliche Qualit&auml;t f&uuml;r Ihre wichtigen Unternehmenstexte zu gew&auml;hrleisten.  </p>

<H3>Kl&auml;rung von Lokalisierungsfragen</H3>
<p>Es ist durchaus m&ouml;glich, dass einige der Texte auf Ihrer Website zwar in Ihrer Ausgangssprache relevant, f&uuml;r fremdsprachliche Leser einer &uuml;bersetzten Version der Website jedoch bedeutungslos sind. Andere Texte m&uuml;ssen eventuell nur minimal angepasst werden, damit sie dem Zielpublikum die von Ihnen gew&uuml;nschte Botschaft effektiver vermitteln. So k&ouml;nnten beispielsweise Gr&ouml;&szlig;enangaben in amerikanische Einheiten umgewandelt oder imperiale Gewichtsangaben neben metrischen in Klammern genannt werden. Zudem kann es sinnvoll sein, die in Ihren Texten aufgef&uuml;hrten Beispiele anhand von Ortsangaben zu veranschaulichen, mit denen das Zielpublikum vertraut ist. Wir k&ouml;nnen Ihnen dabei helfen, die entsprechenden Textstellen so fr&uuml;h wie m&ouml;glich zu benennen, damit Sie Ihre Internetpr&auml;senz genau auf das jeweilige Zielpublikum abstimmen k&ouml;nnen. So sparen Sie auch Geld. </p>

<p>Wahrscheinlich haben Sie bereits Vorgaben zu Terminologie, Stil, Vorgaben und/oder Leitlinien, die Sie bei der Vermittlung Ihrer Botschaft in Ihrer Sprache verwenden.  Der erste Schritt auf dem Weg zu einer qualitativ hochwertigen &Uuml;bersetzung ist &uuml;blicherweise die Erstellung einer &auml;hnlichen Dokumentation hinsichtlich Terminologie, Stil und Vorgaben f&uuml;r die jeweilige Zielsprache. Wir sind auf die Verwaltung mehrsprachiger Terminologie-Glossare unter Verwendung entsprechender Verwaltungssysteme spezialisiert. Wir begleiten Sie durch den gesamten Prozess und unterst&uuml;tzen Sie hinsichtlich aller Fragen, die sich abh&auml;ngig von Ihrer Markenstrategie, dem Zielpublikum und der Art des zu &uuml;bersetzenden Textes bez&uuml;glich Stil und Vorgaben in der englischen Sprache ergeben.</p>

<html>
<body>
<H3>Wir finden die richtigen Worte f&uuml;r Ihr Publikum.</H3>

<p>Lediglich eine &Uuml;bersetzungsanfrage mit der Angabe, einen Text beispielsweise aus dem Deutschen ins Englische &uuml;bersetzen zu lassen, an eine Agentur zu schicken, enth&auml;lt oftmals bei weitem nicht alle Informationen, die erforderlich sind, um dem/der &Uuml;bersetzer/in zu erm&ouml;glichen, die bestm&ouml;gliche Qualit&auml;t zu liefern. Wir fragen unsere Kunden, welche zentrale Botschaft sie vermitteln m&ouml;chten, in welchem Stil diese Botschaft pr&auml;sentiert werden soll und an welches Publikum sie vermittelt werden soll, damit der &Uuml;bersetzer das &bdquo;Wer&quot; und das &bdquo;Warum&quot; kennt, auf dem der Text sich gr&uuml;ndet. Ein technischer Bericht, der sich an ein internationales Publikum aus Ingenieuren richtet, muss beispielsweise anders &uuml;bersetzt werden als eine Website, die haupts&auml;chlich auf den britischen Markt ausgerichtet ist. Wir und unsere &Uuml;bersetzer sind uns dessen absolut bewusst. Wir informieren unsere &Uuml;bersetzer vor Beginn der &Uuml;bersetzungsarbeit &uuml;ber das Zielpublikum und den zu verwendenden Stil. Auf Wunsch erstellen und pflegen wir f&uuml;r unsere Kunden individuelle Stilvorgaben und stellen diese unseren &Uuml;bersetzern bei Bedarf zur Verf&uuml;gung. F&uuml;r unsere &Uuml;bersetzungen ins Englische verwenden wir standardm&auml;&szlig;ig beispielsweise den <a href=http://www.theguardian.com/styleguide target="_newtab">Style-Guide des Guardian</a>.</p>

<p>Wir erstellen und pflegen in Zusammenarbeit mit unseren Kunden Terminologielisten und zweisprachige Glossare. Mit den zu &uuml;bersetzenden Texten stellen wir unseren &Uuml;bersetzern aktualisierte Listen zur Verf&uuml;gung, die w&auml;hrend des &Uuml;bersetzungsprozesses st&auml;ndig erweitert und verbessert werden.  Sofern erforderlich werden &Auml;nderungen und Erg&auml;nzungen regelm&auml;&szlig;ig mit den Kunden besprochen. </p>  

<H3>Wir verbessern Ihre bestehenden &Uuml;bersetzungen</H3>

<p>Das Internet ist ein dynamischer Raum. Es ist sehr wahrscheinlich, dass Sie Ihre Webinhalte von Zeit zu Zeit aktualisieren wollen. Oftmals ist es schwierig, zu verfolgen, welche Inhalte bereits ge&auml;ndert wurden und welche nicht. Mit Language Landscapes ist das kein Thema mehr f&uuml;r Sie. Lassen Sie uns einfach die zu &uuml;bersetzenden Texte in dem von Ihren Webadministratoren und/oder Ihrem Content Management System bevorzugten Format zukommen.  Die von uns f&uuml;r Sie gepflegte &Uuml;bersetzungsdatenbank stellt sicher, dass derselbe Satz nicht zweimal &uuml;bersetzt wird. Ein weiterer Vorteil unserer &Uuml;bersetzungswerkzeuge ist die M&ouml;glichkeit, nach &Uuml;bereinstimmungen in vorhandenen Texten (so genannten &bdquo;Fuzzy Matches&ldquo;) zu suchen. Dadurch wird ein einheitlicher, professioneller Stil gew&auml;hrleistet. Die &Uuml;bersetzungsdatenbank erleichtert zudem die nachtr&auml;gliche Anpassung bereits vorhandener Texte an die jeweils aktuellste Version der genehmigten Terminologie sowie die Einhaltung der jeweils aktuellen Vorgabven hinsichtlich des Stils.</p>

<p>Auch wenn Sie Texte haben, die bereits von einer anderen Agentur oder von eigenen Mitarbeitern &uuml;bersetzt wurden, k&ouml;nnen wir diese mithilfe entsprechender Werkzeuge in unsere Datenbanken integrieren. Jegliche Verbesserungen bzw. Anpassungen, die wir an bestehenden &Uuml;bersetzungen vornehmen, werden unmittelbar in der &Uuml;bersetzungsdatenbank gespeichert. Gegebenenfalls werden alte Versionen &uuml;berschrieben und somit sichergestellt, dass keine Verbesserungen verloren gehen. Der gesamte &Uuml;bersetzungszyklus wird von modernster Technologie aus dem Bereich Ver&auml;nderungsmanagement unterst&uuml;tzt.</p> 

<H3>Teamwork f&uuml;r Quali&auml;t</H3>

<p>In der Verlagsbranche gibt es ein altes Sprichwort, das besagt, dass selbst der talentierteste Auto einen Verleger braucht.  Das gilt auch f&uuml;r die talentiertesten &Uuml;bersetzer.  Nat&uuml;rlich ist der von uns mit dem Projekt betraute &Uuml;bersetzer vorrangig f&uuml;r die &Uuml;bersetzungsarbeit zust&auml;ndig, allerdings sind wir der Ansicht, dass auch eine qualitativ absolut hochwertige Arbeit davon profitieren kann, dass sie von einer weiteren Person gegengelesen wird und dass diese Person dem &Uuml;bersetzer und gegebenenfalls dem urspr&uuml;nglichen Verfasser des Textes wichtige Anregungen liefern kann, die dann Grundlage einer weiterf&uuml;hrenden Diskussion sein k&ouml;nnen. Aus diesem Grund liegt ein wesentlicher Schwerpunkt unseres Arbeitsablaufs auf der Kommunikation zwischen &Uuml;bersetzern, Herausgebern und Korrekturlesern, die alle gemeinsam das &Uuml;bersetzungsteam bilden. Bei Zweifeln, Fragen oder Problemen wird das &Uuml;bersetzungsteam auf eine vorher festgelegte und strukturierte Art und Weise mit dem Kunden und/oder dem urspr&uuml;nglichen Verfasser des Texts kommunizieren. Unsere Erfahrung zeigt, dass dieser Prozess auch dabei helfen kann, potenzielle Verbesserungen am Text in der Ausgangssprache zu ermitteln. Strukturierte Kommunikation lautet unsere Devise.</p>

<p>Unsere &Uuml;bersetzungen werden standardm&auml;&szlig;ig zweimal Korrektur gelesen, um sicherzustellen, dass die &Uuml;bersetzung den f&uuml;nf im Rahen unseres Qualit&auml;tssicherungsprozesses definierten Dimensionen entspricht. Wo immer sich noch nicht behandelte Lokalisierungsfragen in den &uuml;bersetzten Texten finden, werden diese diskutiert und vor Lieferung der fertigen &Uuml;bersetzung in Absprache mit dem Kunden gekl&auml;rt.</p>
