<H3>The translation workflow takes in more than just translation</H3>

<p>Different translation tasks require different processes.  A technical report that simply needs to be understood clearly by colleagues based in another country, for example, needs a different level of quality than a critical interface between you and a strategic market. That's the reason why we have defined a modular workflow containing steps that you can choose to include or leave out of the translation process for your texts.</p>

<p>While the most demanding and time-intensive task in translation tasks will almost always be the work of the translator him or herself, there are a number of steps to complete before the translator can start and after he or she is finished in order to ensure the highest possible translation quality for business critical texts.  </p>

<H3>Check for localisation issues</H3>

<p>It is quite possible that some of the texts appearing on your website in your native language will have little relevance to customers browsing your translated site. Other texts may need small adjustments in order to communicate your message to your target audience more effectively. You might want to convert measurements to suit American units or give British readers imperial weights in brackets beside metric measures, for example. You may want to adjust examples given in your text to include place names familiar to your target audience. We can help you to identify the texts you might need to adjust as early as possible to save you money and fine tune your web presence precisely to your target audience. </p>

<p>You probably have a list of terminology and styles, rules and/or guidelines that you use when communicating your message in your native language.  For high-quality translation the first step in the process is usually to create a similar list of terminology, styles and rules for the target language. We are specialists in managing multilingual terminology glossaries using terminology management systems. We can guide you through the issues that come up in English in relation to styles and rules, depending on your branding strategy, your intended audience and on the type of text being translated.</p>

<H3>Getting the language right for your audience</H3>

<p>Simply sending off a translation to an agency along with an instruction to translate the original from, say, German into English often doesn't provide all the information that the translator needs to do his or her work to the best possible quality. We ask our customers for details on the central message they want to get across, the style in which they'd like to present their message and its intended audience so that the translator knows the whos and whys of behind the web text. A technical report with an international engineering readership, for example, will need to be translated very differently to a home page message written primarily for the British market. We and our translators are well aware of these issues. We brief our translators on the intended audience and style required by the customer before they start any translation work. We draw up and maintain customised style guides for our customers on request and pass them on to translators as necessary. For our translations into British English, for example, we use <a href=http://www.theguardian.com/styleguide target="_newtab">The Guardian Style guide</a> by default.</p>

<p>We create and maintain terminology lists and bilingual glossaries in partnership with our customers. Updated lists are provided to our translators along with the texts to be translated and are progressively extended and improved during the translation process.  Changes and additions will be discussed intermittently with customers where required. </p>  

<H3>Leverage your existing translations</H3>

<p>The web is a dynamic environment. You will almost certainly be updating your web content at regular intervals. It is quite often difficult to keep track of what content has been changed and what hasn't.  With Language Landscapes that isn't an issue. You just send your translatable texts to us as a batch in the format that best suits your web administrators and/or content management system.  The translation memory database that we manage for you on site will ensure that we never translate the same sentence twice. Another benefit of our translation tools are their fuzzy match functionality, which will help ensure that your translations are always written in a consistent, professional style. The translation memory database also makes it easy to modify existing text retroactively so that they always contain the latest approved terminology and follow the most recent style guide rules.</p>

<p>Even where you have texts that have already been translated by another agency or using in-house resources, we can add them into the translation memory database using alignment tools. Any improvements or adaptations we make to existing translations are recorded immediately in translation memories, overwriting the previous version where appropriate, ensuring that improvements are not lost. The whole translation cycle is supported by the latest change management technology.</p> 

<H3>Teamwork for quality</H3>

<p>There is an old saying in the publishing industry that even the most talented author needs an editor.  The same is true of even the most talented translator.  While the main person responsible for the translation work we do is the named translator, we believe that even the best quality work will profit from a person to check the translated text and discuss improvements with the translator and, where necessary, with the original author. That's why our translation workflow puts an emphasis on close communication between translators, editors and proofreaders, who together form a translation team. Where there are doubts, questions or problems the translation team will communicate in an agreed and structured manner with the customer and/or original author. Our experience suggests that process can even help you identify potential improvements to your text in the original language. Structured communication is our watchword.</p>

<p>Our translations are subjected to two standard rounds of proofreading to ensure that each translated text conforms to standards on <?php
echo $this->Html->link('the five quality dimensions','/page/quality',array('target' => '_blank')); ?> defined in our quality assurance process. Where previously unidentified localisation issues are found in the translated texts, we discuss and resolve them in consultation with the customer them before delivering any finished translation.</p>